/**
 * Loads and caches mind-graph snapshot JSONs.
 *
 * Returns:
 *   { manifest, active, snapshot, loading, error, setActive }
 *
 * Data files live under /mind/ on the public site, generated by the brain-vault
 * extractor — see scripts/extract-graph.mjs in themeetpatell/meetpatel-brain.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { z } from "zod";

const Node = z.object({
  id: z.string().regex(/^n_[0-9a-f]{6,8}$/),
  area: z.enum([
    "compass",
    "ventures",
    "areas",
    "atlas",
    "meta",
    "daily",
    "inbox",
    "archive",
  ]),
  size: z.number().int().min(1).max(10),
  createdAt: z.string(),
  lastModifiedAt: z.string(),
});

const Edge = z.object({ s: z.string(), t: z.string() });

const Graph = z.object({
  snapshot: z.string(),
  generatedAt: z.string(),
  vaultCommit: z.string(),
  nodes: z.array(Node),
  edges: z.array(Edge),
  stats: z.object({
    noteCount: z.number().int(),
    edgeCount: z.number().int(),
    addedLast7d: z.number().int(),
    addedLast30d: z.number().int(),
    byArea: z.record(z.number().int()),
  }),
});

const Manifest = z.object({
  latest: z.string(),
  snapshots: z.array(
    z.object({
      month: z.string(),
      file: z.string(),
      vaultCommit: z.string(),
      noteCount: z.number().int(),
    }),
  ),
});

const LRU_CAP = 4;
const BASE = "/mind";

class SnapshotCache {
  constructor() {
    this.map = new Map();
  }
  get(key) {
    if (!this.map.has(key)) return null;
    const v = this.map.get(key);
    this.map.delete(key);
    this.map.set(key, v);
    return v;
  }
  set(key, value) {
    if (this.map.has(key)) this.map.delete(key);
    this.map.set(key, value);
    while (this.map.size > LRU_CAP) {
      const first = this.map.keys().next().value;
      this.map.delete(first);
    }
  }
}

async function fetchJson(url, schema) {
  const res = await fetch(url, { cache: "force-cache" });
  if (!res.ok) throw new Error(`fetch ${url}: ${res.status}`);
  const json = await res.json();
  return schema.parse(json);
}

export function useGraphData() {
  const cacheRef = useRef(new SnapshotCache());
  const [manifest, setManifest] = useState(null);
  const [active, setActive] = useState(null);
  const [snapshot, setSnapshot] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const m = await fetchJson(`${BASE}/index.json`, Manifest);
        if (cancelled) return;
        setManifest(m);
        const latest = m.snapshots[0];
        const g = await fetchJson(`${BASE}/${m.latest}`, Graph);
        if (cancelled) return;
        cacheRef.current.set(latest?.month ?? "latest", g);
        setActive(latest?.month ?? g.snapshot);
        setSnapshot(g);
      } catch (e) {
        if (!cancelled) setError(e);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const loadMonth = useCallback(
    async (month) => {
      if (!manifest) return;
      const cached = cacheRef.current.get(month);
      if (cached) {
        setSnapshot(cached);
        return;
      }
      const entry = manifest.snapshots.find((s) => s.month === month);
      if (!entry) return;
      try {
        const g = await fetchJson(`${BASE}/${entry.file}`, Graph);
        cacheRef.current.set(month, g);
        setSnapshot(g);
      } catch (e) {
        setError(e);
      }
    },
    [manifest],
  );

  const setActiveAndLoad = useCallback(
    (month) => {
      setActive(month);
      loadMonth(month);
    },
    [loadMonth],
  );

  return useMemo(
    () => ({
      manifest,
      active,
      snapshot,
      loading,
      error,
      setActive: setActiveAndLoad,
    }),
    [manifest, active, snapshot, loading, error, setActiveAndLoad],
  );
}
